version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: thealthdb
    ports:
      - "15432:5432"
    environment:
      POSTGRES_DB: thealthdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    environment:
      REDIS_PASSWORD: redis
    command: redis-server
